### ISSUE TITLE
can't run workflow

### ISSUE THREAD

**Issue by hgschmie** [JasonLandbridge/CircuitHUD-V2#12]
<img width="1860" alt="Screenshot 2024-11-23 at 17 11 05" src="https://github.com/user-attachments/assets/f708bb7a-bc24-4cc7-8b2a-aaa3cb67d0e2">

:sadface:

**Comment by JasonLandbridge** [comment]
changed it to this now: 
![image](https://github.com/user-attachments/assets/774789d3-36d6-473b-8561-c0c58c1408a8)

**Comment by hgschmie** [comment]
Now it worked. :-)  It may be a bit safer to choose the last option and list the actions explicitly, but the current setup worked.

**Comment by JasonLandbridge** [comment]
Picked the last option, let me know if it's breaks again
